import { prisma } from '../config/prisma';
import { addDays, isoDate, weekBoundsFromAny } from '../utils/week';
import { generateInsights, type UserTier } from './ai';
import { generateCoverImage } from './ai/imageService';
import { computeEffectiveTier } from './vipService';

// ============================================================
// Weekly summary
// ============================================================

interface CountByKey { [key: string]: number; }

function countBy<T, K extends string>(arr: T[], pick: (x: T) => K | null | undefined): CountByKey {
  const out: CountByKey = {};
  for (const item of arr) {
    const k = pick(item);
    if (k) out[k] = (out[k] ?? 0) + 1;
  }
  return out;
}

function avg(nums: number[]): number | null {
  if (nums.length === 0) return null;
  return Number((nums.reduce((a, b) => a + b, 0) / nums.length).toFixed(2));
}

function topKey(counts: CountByKey): string | null {
  let best: string | null = null;
  let bestN = -1;
  for (const [k, n] of Object.entries(counts)) {
    if (n > bestN) { best = k; bestN = n; }
  }
  return best;
}

export interface WeeklyAnalysisResult {
  weekStart: string;
  weekEnd: string;
  totals: {
    work: number;
    friend: number;
    partner: number;
    gratitude: number;
    reflectionDays: number;
    activeDays: number; // days with at least one record of any kind
  };
  work: {
    count: number;
    byCategory: CountByKey;
    byEmotion: CountByKey;
    avgImportance: number | null;
    topCategory: string | null;
    followUps: number;
  };
  relationship: {
    friendCount: number;
    partnerCount: number;
    friendsContacted: string[]; // distinct names
    partnerInteractions: CountByKey;
    unresolvedArguments: number;
  };
  gratitude: {
    count: number;
    byCategory: CountByKey;
    avgImpact: number | null;
  };
  emotional: {
    /** dayKey YYYY-MM-DD → 当日整体评分 */
    dailyRating: Array<{ date: string; rating: number | null }>;
    avgOverallRating: number | null;
    emotionDistribution: CountByKey; // across all records that have an emotion
  };
  growth: {
    achievements: string[]; // collected from reflection.eveningAchievements
    challenges: string[];
  };
  /** Plain-language insights, generated by rules — no LLM here */
  recommendations: string[];
}

/**
 * Compute a weekly summary from raw records. Pure function over data so it's
 * easy to test and easy to swap in an LLM later.
 */
function buildAnalysis(
  weekStart: Date,
  weekEnd: Date,
  data: {
    work: Array<{ date: Date; category: string; emotion: string; importance: number; followUpAction: string | null }>;
    friend: Array<{ date: Date; friendName: string; interactionType: string; emotion: string; importance: number }>;
    partner: Array<{ date: Date; partnerName: string; interactionType: string; emotion: string; importance: number; resolved: boolean }>;
    gratitude: Array<{ date: Date; category: string; emotion: string; impactLevel: number }>;
    reflection: Array<{ date: Date; eveningAchievements: string[]; eveningChallenges: string[]; overallRating: number | null }>;
  }
): WeeklyAnalysisResult {
  const { work, friend, partner, gratitude, reflection } = data;

  // ----- totals -----
  const dayKeys = new Set<string>();
  [...work, ...friend, ...partner, ...gratitude, ...reflection].forEach((r) =>
    dayKeys.add(isoDate(r.date))
  );

  // ----- work -----
  const workByCategory = countBy(work, (r) => r.category);
  const workByEmotion = countBy(work, (r) => r.emotion);

  // ----- relationships -----
  const friendsContacted = Array.from(new Set(friend.map((r) => r.friendName)));
  const partnerByType = countBy(partner, (r) => r.interactionType);
  const unresolvedArguments = partner.filter((r) => r.interactionType === 'argument' && !r.resolved).length;

  // ----- gratitude -----
  const gratByCategory = countBy(gratitude, (r) => r.category);

  // ----- emotional -----
  const dailyRating: WeeklyAnalysisResult['emotional']['dailyRating'] = [];
  for (let i = 0; i < 7; i++) {
    const day = isoDate(addDays(weekStart, i));
    const r = reflection.find((x) => isoDate(x.date) === day);
    dailyRating.push({ date: day, rating: r?.overallRating ?? null });
  }
  const ratingsOnly = reflection.map((r) => r.overallRating).filter((x): x is number => typeof x === 'number');

  const emotionDistribution: CountByKey = {};
  for (const arr of [work, friend, partner, gratitude]) {
    for (const r of arr) {
      const e = (r as { emotion?: string }).emotion;
      if (e) emotionDistribution[e] = (emotionDistribution[e] ?? 0) + 1;
    }
  }

  // ----- growth -----
  const achievements = reflection.flatMap((r) => r.eveningAchievements).filter(Boolean);
  const challenges = reflection.flatMap((r) => r.eveningChallenges).filter(Boolean);

  // ----- recommendations (rule-based) -----
  const recommendations: string[] = [];

  if (work.length === 0) recommendations.push('本周还没有工作记录 — 试着每天记一件工作上的小成就或挑战');
  else if (work.length >= 15) recommendations.push('工作记录很丰富，注意为自己留出休息时间');

  if (gratitude.length === 0) recommendations.push('本周还没有感恩记录 — 哪怕一句"今天天气好"也能改善心情');
  else if (gratitude.length >= 5) recommendations.push(`感恩习惯保持得很好，本周记录了 ${gratitude.length} 件`);

  if (friend.length === 0 && partner.length === 0) {
    recommendations.push('本周没有人际记录 — 主动联系一位朋友或与伴侣深入聊聊');
  }

  if (unresolvedArguments > 0) {
    recommendations.push(`有 ${unresolvedArguments} 次未解决的争论，找时间复盘并沟通`);
  }

  if (workByEmotion.anxious && workByEmotion.anxious >= 3) {
    recommendations.push('工作中"焦虑"出现较多，考虑列出焦虑源并逐一拆解');
  }

  const reflDays = reflection.length;
  if (reflDays <= 1) recommendations.push('本周三省记录较少 — 早晨定目标、晚上回顾，是 1 分钟的高 ROI 习惯');

  const avgRating = avg(ratingsOnly);
  if (avgRating !== null) {
    if (avgRating <= 2.5) recommendations.push('本周整体评分偏低，留意是否有持续性的压力源');
    else if (avgRating >= 4.5) recommendations.push('本周整体评分很高 — 把感觉好的事记到下周想重复的事项里');
  }

  return {
    weekStart: isoDate(weekStart),
    weekEnd: isoDate(weekEnd),
    totals: {
      work: work.length,
      friend: friend.length,
      partner: partner.length,
      gratitude: gratitude.length,
      reflectionDays: reflDays,
      activeDays: dayKeys.size,
    },
    work: {
      count: work.length,
      byCategory: workByCategory,
      byEmotion: workByEmotion,
      avgImportance: avg(work.map((r) => r.importance)),
      topCategory: topKey(workByCategory),
      followUps: work.filter((r) => r.followUpAction).length,
    },
    relationship: {
      friendCount: friend.length,
      partnerCount: partner.length,
      friendsContacted,
      partnerInteractions: partnerByType,
      unresolvedArguments,
    },
    gratitude: {
      count: gratitude.length,
      byCategory: gratByCategory,
      avgImpact: avg(gratitude.map((r) => r.impactLevel)),
    },
    emotional: {
      dailyRating,
      avgOverallRating: avgRating,
      emotionDistribution,
    },
    growth: { achievements, challenges },
    recommendations,
  };
}

async function loadWeekData(userId: string, weekStart: Date, weekEnd: Date) {
  const dateFilter = { gte: weekStart, lte: weekEnd };
  const [work, friend, partner, gratitude, reflection] = await Promise.all([
    prisma.workRecord.findMany({
      where: { userId, date: dateFilter },
      select: { date: true, category: true, emotion: true, importance: true, followUpAction: true },
    }),
    prisma.friendRecord.findMany({
      where: { userId, date: dateFilter },
      select: { date: true, friendName: true, interactionType: true, emotion: true, importance: true },
    }),
    prisma.partnerRecord.findMany({
      where: { userId, date: dateFilter },
      select: { date: true, partnerName: true, interactionType: true, emotion: true, importance: true, resolved: true },
    }),
    prisma.gratitudeRecord.findMany({
      where: { userId, date: dateFilter },
      select: { date: true, category: true, emotion: true, impactLevel: true },
    }),
    prisma.dailyReflection.findMany({
      where: { userId, date: dateFilter },
      select: { date: true, eveningAchievements: true, eveningChallenges: true, overallRating: true },
    }),
  ]);
  return { work, friend, partner, gratitude, reflection };
}

/**
 * Always recompute from raw records on read — this keeps the summary fresh
 * even if new records were added since the last `generate` call. Generation
 * also persists to weekly_summaries so we have history of past summaries.
 */
export async function computeWeeklySummary(userId: string, weekStartStr: string): Promise<WeeklyAnalysisResult> {
  const { weekStart, weekEnd } = weekBoundsFromAny(weekStartStr);
  const data = await loadWeekData(userId, weekStart, weekEnd);
  return buildAnalysis(weekStart, weekEnd, data);
}

interface SavedExtras {
  coverImageUrl: string | null;
  insightSource: 'ai' | 'rules' | null;
  referencedBooks: Array<{ title: string; author: string }>;
}

/** Cover image + insight source + referenced books from a previous `generate`. */
export async function getSavedExtras(userId: string, weekStartStr: string): Promise<SavedExtras> {
  const { weekStart } = weekBoundsFromAny(weekStartStr);
  const row = await prisma.weeklySummary.findUnique({
    where: { userId_weekStart: { userId, weekStart } },
    select: { coverImageUrl: true, aiRecommendations: true },
  });
  const ai = (row?.aiRecommendations ?? {}) as {
    source?: 'ai' | 'rules';
    referencedBooks?: Array<{ title: string; author: string }>;
  };
  return {
    coverImageUrl: row?.coverImageUrl ?? null,
    insightSource: ai.source ?? null,
    referencedBooks: Array.isArray(ai.referencedBooks) ? ai.referencedBooks : [],
  };
}

export async function generateAndPersistWeeklySummary(userId: string, weekStartStr: string) {
  const { weekStart, weekEnd } = weekBoundsFromAny(weekStartStr);
  const data = await loadWeekData(userId, weekStart, weekEnd);
  const analysis = buildAnalysis(weekStart, weekEnd, data);

  // Pick AI provider by the user's *effective* tier (expiry-aware);
  // falls back to rule-based on any failure.
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: { tier: true, vipExpiresAt: true },
  });
  const tier = (user ? computeEffectiveTier(user) : 'free') as UserTier;

  // Insights + cover image run concurrently; both degrade gracefully on failure.
  const [outcome, cover] = await Promise.all([
    generateInsights(analysis, tier),
    generateCoverImage(analysis),
  ]);

  // The returned analysis carries the (possibly AI-generated) recommendations
  // and a source flag, so the frontend can show "AI 生成" vs "规则生成".
  analysis.recommendations = outcome.recommendations;

  const aiRecommendations = {
    items: outcome.recommendations,
    source: outcome.source,
    provider: outcome.provider ?? null,
    referencedBooks: outcome.referencedBooks,
  };

  const persisted = await prisma.weeklySummary.upsert({
    where: { userId_weekStart: { userId, weekStart } },
    update: {
      weekEnd,
      workAnalysis: analysis.work as object,
      relationshipAnalysis: analysis.relationship as object,
      gratitudeAnalysis: analysis.gratitude as object,
      emotionalAnalysis: analysis.emotional as object,
      growthTracking: analysis.growth as object,
      aiRecommendations,
      // Only overwrite the cover when we successfully generated a new one,
      // so a transient image failure doesn't wipe an existing cover.
      ...(cover.url ? { coverImageUrl: cover.url } : {}),
    },
    create: {
      userId,
      weekStart,
      weekEnd,
      workAnalysis: analysis.work as object,
      relationshipAnalysis: analysis.relationship as object,
      gratitudeAnalysis: analysis.gratitude as object,
      emotionalAnalysis: analysis.emotional as object,
      growthTracking: analysis.growth as object,
      aiRecommendations,
      coverImageUrl: cover.url,
    },
  });

  return {
    analysis,
    summary: persisted,
    insightSource: outcome.source,
    provider: outcome.provider,
    coverImageUrl: persisted.coverImageUrl,
    referencedBooks: outcome.referencedBooks,
  };
}

// ============================================================
// Trends (last N weeks)
// ============================================================

export interface TrendPoint {
  weekStart: string;
  weekEnd: string;
  work: number;
  friend: number;
  partner: number;
  gratitude: number;
  avgRating: number | null;
}

export async function getTrends(userId: string, weeks = 12): Promise<TrendPoint[]> {
  const today = new Date();
  today.setUTCHours(0, 0, 0, 0);
  const points: TrendPoint[] = [];
  for (let i = weeks - 1; i >= 0; i--) {
    const target = addDays(today, -7 * i);
    const { weekStart, weekEnd } = weekBoundsFromAny(isoDate(target));
    const data = await loadWeekData(userId, weekStart, weekEnd);
    const ratings = data.reflection
      .map((r) => r.overallRating)
      .filter((x): x is number => typeof x === 'number');
    points.push({
      weekStart: isoDate(weekStart),
      weekEnd: isoDate(weekEnd),
      work: data.work.length,
      friend: data.friend.length,
      partner: data.partner.length,
      gratitude: data.gratitude.length,
      avgRating: avg(ratings),
    });
  }
  return points;
}
